### PR TITLE
fix notebook MOM6

### PR DESCRIPTION
**Pull request by raphaeldussin**
* updated path for data
* edit and improvements to text
* fix plotting issues https://github.com/xgcm/xgcm/issues/246

### CODE REVIEW

**Comment by jbusecke** [comment]
This seems to have some conflicts with the main branch (I might have commited something that messed things up), please feel free to overwrite the notebook!

**Comment by raphaeldussin** [comment]
I moved it back to failing to make it easier. looks like it's some jupyter metadata. I don't have the rights to fix it

**Comment by jbusecke** [comment]
Let me try...

**Comment by jbusecke** [comment]
Looks great ! https://gallery.pangeo.io/repos/xgcm/xgcm-examples/03_MOM6.html

Thanks for the quick fix @raphaeldussin

**Pull request merged**
